import '../../../../styles/globals.css';
import { Inter } from 'next/font/google';
import LoginHeader from '@/components/LoginHeader';
import LoginFooter from '@/components/LoginFooter';


const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Shita-Kiri-Suzume Blog',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className="max-w-7xl mx-auto">
        <LoginHeader />
        {children}
        <LoginFooter />
        </body>
    </html>
  )
}
